version: '3'
services:
  odoo:
    image: odoo:15.0
    platform: "linux/arm64"
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
    environment:
      - PGHOST=db
      - PGUSER=odoo
      - PGPASSWORD=odoo
    ports:
      - "3773:8069"
      - "2882:8071"
    volumes:
      - odoo15-classes-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra_addons:/mnt/extra-addons
#      - ./odoo:/usr/lib/python3/dist-packages/odoo
  db:
    image: postgres:13
    platform: "linux/arm64"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    ports:
      - "5489:5432"
    volumes:
       - odoo15-classes-db-data:/var/lib/postgresql/data
volumes:
    odoo15-classes-web-data:
    odoo15-classes-db-data: